### ISSUE TITLE
How to render null data object?

### ISSUE THREAD

**Issue by brentonannan** [vt-elixir/ja_serializer#114]
Gday!

According to the spec:

> Primary data MUST be either:
> a single resource object, a single resource identifier object, or null, for requests that target single resources

I'd like to return `{"data": "null"}` for responses to my auth controller (as it returns a bearer token in headers; no data in the body is required), but I can't find a way to do it - even going directly to `format`.

I realise I can just hard-code this, but I'd like to see `render(__MODULE__, data: nil)` return this correctly (as I like the other conveniences like the `jsonapi` being consistent).

Thoughts? Cheers.

**Comment by alanpeabody** [comment]
@brentonannan I haven't really thought this use case through, but would just returning a 204 and not serializing anything work?

I am a bit wary of unexpected behavior if people accidentally pass nil to the serializer, but I will think about it.

**Comment by brentonannan** [comment]
@alanpeabody the problem I have with serialising nothing is that the empty string isn't valid json-api. I'm personally for explicitly passing the data you want serialised, but I appreciate the handiness of a bit of introspection and automation.

**Comment by alanpeabody** [comment]
I guess my question is, if you accidentally return nil from a query, such as if your controller looks like this:

```elixir
render(conn, :show, Repo.get(__MODULE__, params["id"]))
```

Do we want to return `"data": "null"` there? Or is it better to raise an exception? The controller should return 404 with an error object really.

One problem is that JSON-API is so much bigger then just serialization.

**Comment by brentonannan** [comment]
I would think you should return `{"errors":[{"detail":"Not Found"}]}` with a 404 in such a case - I tend to use `get!` and friends myself.

As for my specific use case, I'm gonna follow the convention suggested [here](http://discuss.jsonapi.org/t/json-api-response-format-for-non-resource-data-like-oauth-token/74/3) and render the token in the body as well as putting it in the header.

I still think there's a use case for rendering nil data for your package, but won't be using it right now, so I guess it's up to you whether to close the issue or not; I'd be happy to keep discussing it, and possibly help with implementation.

**Comment by lypborges** [comment]
This looks a little old, but I think what @brentonannan said: 

> I would think you should return {"errors":[{"detail":"Not Found"}]} with a 404 in such a case - I tend to use get! and friends myself.

Make sense and will let we remove boilerplate code from the controller. Let me known if we can help.

**Comment by beerlington** [comment]
This was addressed with https://github.com/vt-elixir/ja_serializer/pull/181
