### ISSUE TITLE
Generator's controller update test is a false positive

### ISSUE THREAD

**Issue by codyjroberts** [vt-elixir/ja_serializer#149]
I'm putting together an example application to aid in the documentation of [json_api_assert](https://github.com/DockYard/json_api_assert) and I found an issue with one of the generated `ja_serializer` tests.

https://github.com/AgilionApps/ja_serializer/blob/master/priv/templates/ja_serializer.gen.phoenix_api/controller_test.exs#L97-L110

``` elixir
 test "does not update chosen resource and renders errors when data is invalid", %{conn: conn} do
    <%= singular %> = Repo.insert! %<%= alias %>{}
    conn = put conn, <%= singular %>_path(conn, :update, <%= singular %>), %{
      "meta" => %{},
      "data" => %{
        "type" => "<%= singular %>",
        "id" => <%= singular %>.id,
        "attributes" => @invalid_attrs,
        "relationships" => relationships
      }
    }

    assert json_response(conn, 422)["errors"] != %{}
  end
```

The error actually comes from the fact that the model is empty to begin with.  When replaced with:

``` elixir
  test "does not update chosen resource and renders errors when data is invalid", %{conn: conn} do
    <%= singular %> = %<%= alias %>{}
                      |> <%= alias %>.changeset(@valid_attrs)
                      |> Repo.insert!

    conn = put conn, <%= singular %>_path(conn, :update, <%= singular %>), %{
      "meta" => %{},
      "data" => %{
        "type" => "<%= singular %>",
        "id" => <%= singular %>.id,
        "attributes" => @invalid_attrs,
        "relationships" => relationships
      }
    }
```

the test fails.  Passes when an actual invalid attribute is entered.  Haven't worked with generators before so I'm not sure how to go about getting actual invalid attributes.  

you can reproduce with
https://github.com/codyjroberts/ja_serializer/tree/fix_controller_test

and heres an example app
https://github.com/codyjroberts/ja_bug

**Comment by alanpeabody** [comment]
Good find, thanks @codyjroberts. I don't actually use this generator (or really generators in general) so I really appreciate you opening an issue!

How do the default phoenix json generators handle this situation?

**Comment by codyjroberts** [comment]
Ah good point.  I'll check the Phoenix source later today and see if I can figure this out.

**Comment by codyjroberts** [comment]
Seems to be an issue in Phoenix too.  

https://github.com/phoenixframework/phoenix/issues/1849
