### ISSUE TITLE
DateTimes lose timezone information when using Ecto 2.0

### ISSUE THREAD

**Issue by KronicDeth** [vt-elixir/ja_serializer#158]
Ecto 2.0 dropped the "Z" from `Ecto.DateTime.iso8601` because `%Ecto.DateTime{}` is timezone naive (it doesn't have to be UTC, it can be whatever timezone the database is using natively).  This means that on upgrade from Ecto 1.X to Ecto 2.X with ja_serializer, views can lose the "Z" in their serialized timezones.

I'm not sure if this should be a warning in ja_serializer's README, or if there should be a configuration option to assume a timezone for `Ecto.DateTime` encoding to allow the "Z" to be added back, so the output matching ja_serializer with Ecto 1.X.  Is ja_serializer calling `to_iso8601` directly even?

**Comment by Moxide** [comment]
Hello, 
This is exactly what I just faced ! A two hour shift in all inserted_at and updated_at fields, showing in my Ember frontend, just because of the missing 'Z' :-)
Currently isn't there a way to customize the output of Ecto.DateTime fields ?

**Comment by alanpeabody** [comment]
Ecto.DateTime are just passed directly through to Poison, Ecto itself defines how those are encoded in poison: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/poison.ex

Not really sure how and even if ja_serializer should handle this. Thoughts?

**Comment by Moxide** [comment]
Well, in the particular case of autogenerated date fields, if you look at `autogenerate` definition in `Ecto.DateTime.Utils` :
```
def autogenerate(:sec) do
    {date, {h, m, s}} = :erlang.universaltime
    erl_load({date, {h, m, s, 0}})
end
```
It seems that Ecto is autogenerating `inserted_at` and `updated_at` fields in UTC format.
So there is something wrong : we receive an ISO8601 date with no timezone, which means it's **local time**.
I think that since it's Ecto's choice to store in UTC, Ecto itself should indicate that those dates are UTC.

In the general case, It should be the job of a 'calendar' library (Calendar, Timex... etc) to handle this.

Basic thoughts from a beginner in Elixir ;-)

**Comment by jfcalvo** [comment]
Same issue here, any more thoughts or any solution for this problem?

**Comment by alanpeabody** [comment]
@jfcalvo ja_serializer just passes Ecto.DateTime (and native DateTime) structs to poison without converting or encoding in anyway. I don't know where Ecto.DateTime is encoded anymore, but you can see how the Elixir 1.3 structs are encoded here: 

https://github.com/devinus/poison/blob/master/lib/poison/encoder.ex#L342-L348

**Comment by swr** [comment]
Ran into this too. Not sure how to solve...but wanted to try and stir up the discussion again. (I am happy to be corrected on anything below, striving for full accuracy...) It started with Ecto 2 switching to using NaiveDateTime to store timestamps into the DB and spitting them out without the Z at the end. In certain JSON parsing libraries (javascript) this causes them to be treated as local time zone by default...though in Ecto land they are UTC.

For now, I am just manually casting the NaiveDateTime to DateTime in UTC where I need them.

```
  def updated_at(camera, conn) do
    DateTime.from_naive!(camera.updated_at, "Etc/UTC")
  end
```

Alternatively I could have changed my store in Ember Data to process the fields with moment.js and flag them as UTC.

http://blog.skylight.io/bringing-sanity-to-javascript-utc-dates-with-moment-js-and-ember-data/

However, that felt more awkward for some reason and could have led to some performance problems as I have some models with a lot of datetime fields that I use.

While I agree that this is probably Ecto's responsibility/concern/fault... seeing as ja_serializer is a presentation/formatting layer on top of Elixir, but frequently used on top of Ecto, it might be something that ja_serializer could "correct" until Elixir gets full fledged timezone support and this problem either goes away or gets worse.

Maybe a "assume naive date times are all UTC" flag at the render call level? Or at the view definition level? I believe this is what @KronicDeth was discussing in the first post.

Thoughts?

**Comment by KronicDeth** [comment]
Our timestamps have `Z` on them now:

```
 "{\"result\":{\"jsonapi\":{\"version\":\"1.0\"},\"data\":{\"type\":\"...\",\"id\":\"1\",\"attributes\":{\"updated-at\":\"2017-03-14T23:48:06.000000Z\",\"inserted-at\":\"2017-03-14T23:48:06.000000Z\",\"deleted-at\":null}}},\"jsonrpc\":\"2.0\",\"id\":\"59347756-4b52-48cd-a15b-c4c55e0b8620\"}"
```

I believe this is a side-effect of doing

```
@timestamps_opts [type: :utc_datetime, usec: false]
  schema "..." do
```

in our schema, so that the DateTimes in the `Ecto.Schema` aren't `NaiveDateTime.t`, but `DateTime.t` with UTC timezone, so `Z`.

**Comment by swr** [comment]
I can confirm the same. Setting that per [hex docs](https://hexdocs.pm/ecto/0.11.1/Ecto.Schema.html#timestamps/1) does indeed add back the Z by making them :utc_datetime.

This fixed all my schema timestamps.

Changing my other timestamp fields from :naive_datetime to :utc_datetime fixed it there as well.

Makes sense that there would be a way to denote this behavior at the ecto level.

Thanks @KronicDeth for the fix and @alanpeabody for the original pushback.

I agree that this can be closed.
