### ISSUE TITLE
Raise exception when attributes/1 macro defines an attribute with the same name as a callback.

### ISSUE THREAD

**Issue by alanpeabody** [vt-elixir/ja_serializer#175]
In particular `type`, `format`, `id`, `preload`, `relationships`, `attributes`, `links`, and `meta` will cause some funky behavior. In those cases just using the attributes/2 callback is better.

**Comment by rynam0** [comment]
I ran into this issue with an upgrade from `0.9.0` to `0.11.0`.
Before upgrading, I was able to serialize an attribute called `links` but this raises in `0.11.0` as you indicate would be expected. I just wanted to confirm this issue and can provide more details if you would like.  I will be looking into how I might use the `attributes/2` callback for now.  Thanks!

**Comment by alanpeabody** [comment]
Another example: https://github.com/AgilionApps/ja_serializer/issues/188
