### ISSUE TITLE
MyMod.format/3 deprecation makes piping impossible

### ISSUE THREAD

**Issue by pinx** [vt-elixir/ja_serializer#178]
I can no longer write this:

```
body = order
|> OrderSerializer.format()
|> Poison.encode!()
```

What is the reason we don't want MyMod.format? I'm hoping to learn more about idiomatic Elixir.

**Comment by alanpeabody** [comment]
@pinx, it is considered an anti pattern to define functions when `use`d that are not default implementations of callbacks.

Once that function is removed you will be able to define your own format function on your module.

**Comment by sbatson5** [comment]
Is there an open issue for updating the ReadMe to use the new syntax?

**Comment by alanpeabody** [comment]
Oh, no I didn't realize it hadn't been updated. PRs welcome!

**Comment by beerlington** [comment]
Closed by https://github.com/vt-elixir/ja_serializer/pull/209
