### ISSUE TITLE
How to only serialize a has_one link if the foreign key id is not nil?

### ISSUE THREAD

**Issue by DCameronMauch** [vt-elixir/ja_serializer#179]
I have a recursive model, with a parent_id column that references it's own id.  But using this methodology, a root model has a nil parent_id.  I want the JSON to contain the parent relationship, but only when that parent_id is not nil.  Is there a way to accomplish this?

As an alternative, I was thinking about just always setting the `has_one :parent, link: "/model/:id/parent"`. and having another controller method for that, but it sort of implies that the object has a parent, which is may not.  And if it doesn't, then what should that URL return?  Empty object, 404, something else?

**Comment by alanpeabody** [comment]
@DCameronMauch I would probably look at using the relationships/2 callback instead of the DSL in this case.

```elixir
def relationships(_conn, struct) do
  struct
  |> parent_relationship
  |> Map.merge({
    other: %HasMany{data: struct.other, serializer: OtherView}
  })
end

def parent_relationship(%{parent_id: nil}), do: %{}
def parent_relationship(%{parent_id: parent_id}) do
  %{
    parent: %HasOne{link: [related: "/parent/#{parent_id}"]}
  }
end
```

You could try using super(conn, struct) in the relationship and still use the DSL for other relationships, but I haven't tried that to be honest.
