### ISSUE TITLE
JSON Not Adhering to Preload Order

### ISSUE THREAD

**Issue by t2** [vt-elixir/ja_serializer#183]
I am trying to have my included associations ordered in a specific manner. The JSON is not adhering to the order I set in the controller. Am I doing something wrong or is this not possible?

```
def show(conn, %{"token" => token}) do
    render conn, "show.json-api", data:
      Repo.get_by!(Pack, token: token)
      |> Repo.preload(designations: from(d in Designation, order_by: [desc: d.order]))
end
```

When the JSON is returned, it is not properly ordered.

**Comment by alanpeabody** [comment]
I am not sure that this is currently possible based upon how including data works. To prevent duplicates includes are converted to a map before being converted back to an array, which would change ordering.

Unfortunately I don't foresee a solution for this that isn't "don't include ordered data" or "sort it again on the client". :-/

**Comment by t2** [comment]
Ok, thanks. I am trying to convert my Rails API over and seeing what is possible. No way to hook into the de-duplication and have it yield to a specific code block that I pass in?

**Comment by alanpeabody** [comment]
Not currently, the order in the relationship key (`data/relationships/designations/data`) should be maintained though. It is just the `included` section which can not be ordered (which can be shared and have multiple types of data).

To be honest ordering in the "include" doesn't seem practical or feasible with how complicated that logic has to be to handle duplicates, optional includes, nested includes, recursive includes, etc.

**Comment by johnmosesman** [comment]
@alanpeabody Is this still something that would be difficult to implement? Or is there a way to give a function hook to change the ordering of a specific association?
