### ISSUE TITLE
Pagination links with base_url breaks for localhost:4000 in frag_for_context/2

### ISSUE THREAD

**Issue by stefanberndtsson** [vt-elixir/ja_serializer#184]
When playing around with Phoenix and ja_serializer to produce json-api data for an Ember app I came to pagination. Pagination works just fine, but the Ember app is separate from the Phoenix server, so the links should have a proper url. 

Using base_url works fine, but during development I want to use ports and then it fails. With the base_url set to "http://localhost:4000" (or anything with a ":" basically, it is caught by frag_for_context/2 which tries to call the function "4000"/2 which of course doesn't exist.

Is there a workaround that I'm missing, or is this something that just won't work? I realise it's not really an issue when deploying to a production scenario, but it is one during development.

**Comment by alanpeabody** [comment]
@stefanberndtsson This should be fixed in master, but I will ship a release with it as well this week.
