### ISSUE TITLE
ja_serializer.gen.phoenix_api does not convert underscore to dash 

### ISSUE THREAD

**Issue by mikeni** [vt-elixir/ja_serializer#186]
the line

https://github.com/AgilionApps/ja_serializer/blob/master/priv/templates/ja_serializer.gen.phoenix_api/controller_test.exs#L45

if my attribute is "my_field", it should be "my-field"

**Comment by mikeni** [comment]
Ok I realize there is another issue with the links

     code:  response["links"]["self"] == "/api/v1/boost-creatives?boost_id=#{boost.id()}&page[page]=1&page[page-size]=#{page_size}&page_size=#{page_size}"
     left:  "/api/v1/boost_creatives?boost_id=839&page[page]=1&page[page-size]=20&page_size=20"
     right: "/api/v1/boost-creatives?boost_id=839&page[page]=1&page[page-size]=20&page_size=20"

I realize the convention should be declared in the config,  either camelcase, hyphen, or snake
or at least some sort function where every member can be formatted

the generation of these vl

**Comment by habeel** [comment]
@mikeni I had a similar issue but I believe if you add plug JaSerializer.Deserializer to your route that should take care of converting 'my_field' to 'my-field'
