### ISSUE TITLE
Is there an easy way to serialize a record into a JSON API object with ALL attributes and relationships?

### ISSUE THREAD

**Issue by begedin** [vt-elixir/ja_serializer#196]
The use case for this would be quickly generating payloads for POST or PATCH requests in tests.

Right now, in our project code-corps/code-corps-api, we have an ex_machina strategy which uses a built record, find it's associated view, and then uses that view to render a JSON API payload.

https://github.com/code-corps/code-corps-api/blob/develop/test/support/strategies.ex

That works quite elegantly, but we have use cases where for example, the controller is expecting a certain set of attributes for a POST request, but renders a different set of attributes for a SHOW response, so that sort of strategy then becomes useless.

Ideally, there would be a way to access or define a "serialize everything" serializer, in other words, one that would render
* all attributes (including virtual attributes)
* all relationships (or at least, all has_one relationships)

Is such a thing possible right now?

**Comment by alanpeabody** [comment]
It is not built in currently, I have been watching https://github.com/DockYard/json_api_assert to begin using that as it matures to help with the testing situation.

A serializer that serialized all attributes and relationships would be fairly easy using https://hexdocs.pm/ecto/Ecto.Schema.html#module-reflection. It might look something like:

```elixir
defmodule AllSerializer do
  use JaSerializer, dsl: false

  def attributes(_conn, struct) do
    struct
    |> Enum.reject(fn({k, _v}) -> Atom.to_string(k) =~ "__" end)
    # reject ids? any other "meta" attributes the above does not catch from ecto?
  end

  def relationships(_conn, %{__struct__: module} = struct) do
    Enum.map module.__schema(:associations), fn(assoc) ->
      # build map of key/relationship structs based on associations.
      # for structure see https://hexdocs.pm/ja_serializer/JaSerializer.Serializer.html#c:relationships/2
    end
  end
end
```

**Comment by begedin** [comment]
I was considering module reflection myself and eve had a go at trying it out, but didn't want to reinvent the wheel if there's something out there already.  `JsonApiAssert` seems like it could do the trick for us, with the strategy approach. I'll post an update here when I get around to seeing how it goes.

**Comment by zachdaniel** [comment]
Ecto model introspection is really good.  `module.__schema__(:fields)` gets you the list of fields, and `module.__schema__(:associations)` (I think) gives you relationships.  Then you can get data about each of those from `module.__schema__(:field, :my_field)` and `(module.__schema__(:association, :my_association)` respectively.

**Comment by beerlington** [comment]
Closing this since I think it's outside the scope of the project
