### ISSUE TITLE
Customize Error Messages?

### ISSUE THREAD

**Issue by nmcalabroso** [vt-elixir/ja_serializer#197]
How do we customize error messages using `JaSerializer`? Specifically, how to override `JaSerializer.EctoErrorSerializer` since, in my opinion, it's not following the spec given by [json-api](http://jsonapi.org) in rendering errors. See this [example](http://jsonapi.org/examples/#error-objects-basics) from the specification itself that says:

> The title and detail members are similar, but detail is specific to this occurrence of the problem, whereas title is more generic.

However, `JaSerializer.EctoErrorSerializer` is returning an arguably specific error that is almost the same with the detail. See this:
```
# from the EctoErrorSerializer
%{"errors" => [%{
  "detail" => "Username should be at least 5 character(s)",
  "source" => %{"pointer" => "/data/attributes/username"},
  "title" => "should be at least 5 character(s)"}]}
```

I want to replace the `title` field to "Attribute too short" just to be consistent and align with the specification. How do we handle this case? I'm thinking of making a way to easily override error serializers instead of correcting `EctoErrorSerializer` itself.

PS. Thank you for the effort in this project! 💯

**Comment by alanpeabody** [comment]
@nmcalabroso I think the easiest way would be to define your own error serialization logic, you could do this using the phoenix built in changeset view and JaSerializer.ErrorSerializer pretty easily. You would then just render the changeset view from the controller.

I don't what the custom logic for setting title would look like, but I would be interested in what you come up with.

**Comment by nmcalabroso** [comment]
@alanpeabody Yeah. I'm going with that route for now. Putting a new function in my controller logic to serialize error - which is basically bypassing `EctoErrorSerializer`.

Going to close this ticket for now. But do you think this is something worth discussing about?
