### ISSUE TITLE
conditional include of relationships?

### ISSUE THREAD

**Issue by rogboone** [vt-elixir/ja_serializer#201]
Newly working with JSON and trying to understand how to return or not return related data from a Phoenix backend.  I'm thinking for example "/meetings" would just return a list of meetings (without any related data), but "/meetings/1" would return the information about meeting id "1" along with any data from a "has_many" relationship (has_many: notes) for example.  In the Phoenix "MeetingView" I have:

``
has_many: notes,
  serializer: Meetings.NoteSerializer,
  include: true
``
But when I do this the "/meetings" url will return all the meetings and all the serialized notes for all the meetings.  Is there a way to include related data only if the request is for a specific meeting eg. "/meeting/1"?

**Comment by alanpeabody** [comment]
Yup, checkout the docs here particurally the "Conditional Inclusion" section):
https://hexdocs.pm/ja_serializer/JaSerializer.DSL.html#has_many/2 

And the json api spec for an example here: http://jsonapi.org/format/#fetching-includes

The `include` key on the relationship is if it should be included by default, the include option will override it if provided.

**Comment by rogboone** [comment]
Thanks much!  I'm at my day job, but just gave it a quick test and I think it's doing what I expect.
