### ISSUE TITLE
Meta on has many relationships.

### ISSUE THREAD

**Issue by zachdaniel** [vt-elixir/ja_serializer#202]
Hey guys!  I really need to find a way to include metadata on the resource identifiers for many to many relationships.  It would be really great, if there was a way to return things in the form of `{record, meta}` from the `JaSerializer.DSL.has_many` function for this purpose.  Any thoughts?  I will need to hack together something soon if there isn't already a way to do it, so I may make a PR for this depending on your thoughts.

**Comment by beerlington** [comment]
This no longer seems relevant because the associated PR was closed https://github.com/vt-elixir/ja_serializer/pull/203
