### ISSUE TITLE
Trouble saving data through ja_seralizer generated controller; ecto says required fields missing?

### ISSUE THREAD

**Issue by nemmons** [vt-elixir/ja_serializer#204]
Hi, i hope it's not inappropriate to ask a question about ja_serializer usage here. I'm having some trouble and hoping for some advice.

I was able to set up an ember front-end with a phoenix backend using ja_serializer, and it works fine when creating/editing records for a simple model with one field: 'title'. 

Now my second model has fields like 'question_text' and i'm getting errors from the server that required fields are missing. i'm wondering if it has to do with improper uses of dashes vs underscores or something along those lines.

here's my phoenix model + controller code along with a sample request and response error message. If anyone could point me in the right direction I'd really appreciate it. https://gist.github.com/nemmons/b23c7f80e97661e2a4478ccfb37ddb9b

**Comment by alanpeabody** [comment]
Are you using https://hexdocs.pm/ja_serializer/0.11.2/JaSerializer.Deserializer.html ?

**Comment by nemmons** [comment]
Ah. No, i was not. Added it to my pipeline and everything is working beautifully now. Thanks very much - I guess i missed that when reading through the documentation.
