### ISSUE TITLE
Allow JSON objects and arrays as attributes

### ISSUE THREAD

**Issue by pinx** [vt-elixir/ja_serializer#208]
The JSON-API allows putting child objects in attributes
> Complex data structures involving JSON objects and arrays are allowed as attribute values.

JaSerializer runs into an error in Poison.encode: unable to encode {nil, "comments"}
Poison can serialize maps, so it seems a matter of handing it over from JaSerializer.

**Comment by alanpeabody** [comment]
Anything not explicitly implemented here is passed as is to Poison: https://github.com/vt-elixir/ja_serializer/blob/master/lib/ja_serializer/formatter.ex.

While Poison does encode maps, I do not believe it will encode tuples (which is what your example abut it) as there isn't really a JS equivalent.
