### ISSUE TITLE
** (Mix) The task "ja_serializer.gen.phoenix_api" could not be found

### ISSUE THREAD

**Issue by darkbushido** [vt-elixir/ja_serializer#220]
I'm kinda new to Phoenix/Elixir so please forgive me if i'm missing something obvious.
When I try to use the generator with version 0.11.2 the ja_serializer.gen.phoenix_api could not be found
```
 mix ja_serializer.gen.phoenix_api
** (Mix) The task "ja_serializer.gen.phoenix_api" could not be found 
```

I have rolled back to 0.11.1 and the generator is working.
```
elixir --version
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.4
```

**Comment by RaphSfeir** [comment]
I had the same issue. I solved it by changing the first line of `ja_serializer/lib/mix/tasks/ja_serializer.gen.phoenix_api.ex` from 

```elixir
if Code.ensure_loaded?(Phoenix) do
```

To

```elixir
if Code.ensure_loaded?(Mix.Phoenix) do
```
To be honest, I'm not sure on what exactly caused this line to block the code but that solved it for me.

**Comment by RaphSfeir** [comment]
Got the same problem, thought I solved it at first but I didn't fully understand what was going on. 

Basically I think the task is available if the `Phoenix` module is loaded and available when compiling `ja_serializer`. So, it could be only a compilation order issue.

First make sure `Phoenix` is available running `mix deps.compile phoenix` to compile it. 

Then clean your local version of `ja_serializer` using : `mix deps.clean ja_serializer` and get it again `mix deps.get && mix deps.compile`. 

Hopefully task will be available in this: `mix help`. You can check available modules at any time in your `_build/dev` folder.
