### ISSUE TITLE
(KeyError) key :users not found in: %{id: , name: , uuid: }

### ISSUE THREAD

**Issue by codecakes** [vt-elixir/ja_serializer#221]
I have some issues around using ja_serializer ver   0.11.2.
In the View file, Sometimes when I try to put a relationship provided in the attributes like:
attributes [:id, :name, :fieldA]

```
has_one or has_many :fieldA,
link: [...],
include: true,
serializer: fieldAView

```
I get an error like ja_serializer (KeyError) No such key found.
I also get sometimes a variation in this error like no such key or function in say for instance `UserView.key` where key probably is an attribute of `fieldA`. The moment I set the include to false :

```
has_one or has_many :fieldA,
link: [...],
include: false,
serializer: fieldAView
```

everything works, but ofcourse the `:fieldA` is not loaded then.

**Comment by beerlington** [comment]
Hi @codecakes I'm having a little trouble understanding what your use case is. Could you provide some more clarification or examples please?
