### ISSUE TITLE
Does ja_serializer require ecto?

### ISSUE THREAD

**Issue by rschooley** [vt-elixir/ja_serializer#227]
I am sending it a list of maps (or structs) to ja_serializer and the results look wonky:

```
[{
  "jsonapi":{
    "version":"1.0"
  },
  "data":[{
    "type":"user",
    "id":"1",
    "attributes":{
      name: "First"
    }
  }, {
    "type":"user",
    "id":"2",
    "attributes":{
      name: "Second"
    }
  }]
}]
```

View:

```
defmodule FooWeb.UserView do
  use FooWeb.Web, :view
  use JaSerializer.PhoenixView

  attributes [:name]
end
```

Controller:

```
users = [%{id: 1, name: "one"}, %{id: 2, name: "two"}]
render conn, "index.json-api", data: users
```

**Comment by alanpeabody** [comment]
@rschooley Ideally no it does not require ecto. What you are showing there looks good to me except the list wrapping the response, which seems unrelated to the data passed in. Is that the only thing you are seeing not working?

**Comment by rschooley** [comment]
I wasn't expecting the `name` prop to be on a nested `attributes` prop but rather a sibling of `id`.

```
{
  "type":"user",
  "id":"2",
  "name": "Second"
}
```

Also, I didn't ask for `type`, can that be trimmed too?

Thanks for the reply!

**Comment by alanpeabody** [comment]
@rschooley this returns only json as per the JSON-API.org spec. If you run into something that doesn't match the spec let me know, but attributes and type is as expected.

**Comment by rschooley** [comment]
Ahh I see now.  Thanks for clarifying man.
