### ISSUE TITLE
Allow raw params to be used as opts during render

### ISSUE THREAD

**Issue by bcardarella** [vt-elixir/ja_serializer#228]
The current implementation requires you to pass a keyword list as the render opts. However, the JSON API spec says these opts should be controlled via the query params. The query params come in as a map with binary keys. We should be able to pass this raw params map as the render opts.

**Comment by alanpeabody** [comment]
The use of keyword lists for opts is... unfortunate. I started moving away from it a bit in the 1.4 update, however I have not gotten around to taking it further. Help would be most welcome.

In regards to allowing the values directly, I am hesitant to make it really easy pass params through without some sort of control/security enforced. JaResource has some callbacks to do some of that, but I have been conservative with raw input there as well.

**Comment by bcardarella** [comment]
> allowing the values directly

I agree, but it should probably be up to the implementing developer to scrub the map
