### ISSUE TITLE
Pagination offset and limit values harcoded

### ISSUE THREAD

**Issue by bcardarella** [vt-elixir/ja_serializer#231]
The pagination rules for Scrivener make an assumption of `number` and `size` for the pagination names. However, the json-api spec notes that other pagination strategies can be used like `offset` and `limit` which would be a zero-based index value. It seems the current implementation wouldn't support this value despite the key names being configurable.

**Comment by alanpeabody** [comment]
Yeah, it does not currently support this in the built in scrivener implementation. You can still do whatever you want with a custom pagination solution, but I realize that is less then ideal if you are already using scrivener.

I would welcome a PR to customize these params though!
