### ISSUE TITLE
include for relationships of great depths

### ISSUE THREAD

**Issue by bcardarella** [vt-elixir/ja_serializer#237]
See Q here: https://elixirforum.com/t/ecto-preload-for-tag-has-many-tags/4323

This Q is the result of ja_serializer requiring associations to be preloaded in order the serialize, which makes sense. However, it isn't clear to me if the above is even possible to resolve if depth isn't known. And considering that there will always be a NotLoaded association, which will cause serialization error.

The short-term fix is to not include the relationship, then provide an endpoint for that resource. However, this I feel puts an undue burden on the api to do so many individual requests when it should be possible via the index action

**Comment by alanpeabody** [comment]
@bcardarella really the only thing I can suggest is a bit of a hack and is a great way to ruin performance: match the not loaded struct and query the repo.

EG:

```elixir
defmodule TagView do
  use JaSerializer.PhoenixView

  has_many :tags

  def tags(%Tag{tags: %Ecto.Association.NotLoaded{}} = tag, _conn) do
    Repo.preload(tag, :tags).tags
  end
  def tags(tag, _conn), do: tag.tags
end
```

**Comment by beerlington** [comment]
Closing this issue since it seems outside the scope of JaSerializer.
