### ISSUE TITLE
Params.to_attributes should use the key formatters

### ISSUE THREAD

**Issue by habeel** [vt-elixir/ja_serializer#238]
It seems like Params.to_attributes is responsible for mapping a json-api payload to a model but right now when it comes to attributes its simply merges the data["attributes"] which is inconsistent with the way the serializer works. I believe the correct thing to do would be to use the ParamParser.parse on the attributes before merging.

ex. if I have a field on the model called "paid_at" by default it gets serialized as "paid-at" but the controller expects you to pass a "paid_at" when creating / updating.

Please let me know if you agree.

**Comment by habeel** [comment]
#239 just created this pull request. I am new to elixir so please feel free to change it up before merging. Regards

**Comment by alanpeabody** [comment]
@habeel this shouldn't be required, `plug JaSerializer.Deserializer` which you should have in your pipeline should already do this for you.

**Comment by habeel** [comment]
@alanpeabody hey alan thanks you are right I somehow missed that while using it in my project.
