### ISSUE TITLE
Unable to use preload for include

### ISSUE THREAD

**Issue by ghoshnirmalya** [vt-elixir/ja_serializer#244]
When I'm calling the api for `blogs`, I also want the data for the `author` to come in the `included` format. You can check here: https://github.com/ghoshnirmalya/social_app_api/blob/master/web/views/blog_view.ex.

It doesn't show the attributes of the `user` model even if I use the following code (here: https://github.com/ghoshnirmalya/social_app_api/blob/master/web/views/blog_view.ex#L6):

```
has_one :author,
    link: :user_link,
    serializer: SocialAppApi.UserView,
    include: true
```

I'm fairly new to Phoenix. Any help to fix this will be highly solicited :)

**Comment by ghoshnirmalya** [comment]
Also, if i use:

```
has_one :author,
    link: :user_link,
    serializer: SocialAppApi.UserSerializer,
    include: true,
    field: :author
```

and 

```
blog = Repo.get!(Blog, id) |> Repo.preload([:author])
render(conn, "show.json-api", data: blog, opts: [include: "author"])
```

it throws me:

```
%UndefinedFunctionError{arity: 2, exports: nil, function: :type,
 module: SocialAppApi.UserSerializer, reason: nil}
```

**Comment by snewcomer** [comment]
@ghoshnirmalya Did you fix your error?

**Comment by ghoshnirmalya** [comment]
@snewcomer Yes. In my controller, I'm using it like:

```
blog = Repo.get!(Blog, id)
      |> Repo.preload(:author)
      render(conn, "show.json-api", data: blog)
```

And my view is like:

```
has_one :author,
    link: :user_link,
    serializer: SocialAppApi.UserView,
    include: true
```

**Comment by snewcomer** [comment]
@ghoshnirmalya I'm wondering if you include at the controller level, you avoid an n+1 problem?  My first thought is for the controller case, the db query will also get authors in one trip.  If at the view layer, it has to make another trip to the db for the author.  

I follow [this](https://github.com/vt-elixir/ja_serializer#phoenix-usage) and it works great for me.

@alanpeabody sry for the ping, but is this true regarding using `include` in the controller vs the view?

**Comment by alanpeabody** [comment]
@snewcomer running Repo.preload in the controller or the special preload/3 callback should both avoid n+1.

If you do it in an attribute/relationship function it will be an n+1 issue.
