### ISSUE TITLE
How to serialize included relationships?

### ISSUE THREAD

**Issue by ravernkohdev** [vt-elixir/ja_serializer#247]
When the request is `/posts/1/relationships/comments?include=comment.author`, JSON API states that we should have all the comment data and the author data of each comment in the included object. However, if I use something like `CommentView` to render this, I cannot include comment data in the included object, right? If so, how do I use JaSerializer to render?

**Comment by alanpeabody** [comment]
JaSerializer currently does not support the /relationships patterns. I have never actually used it and at this point there are no plans to support it. Sorry!
