### ISSUE TITLE
Typo in pagination section of docs

### ISSUE THREAD

**Issue by tjjjwxzq** [vt-elixir/ja_serializer#248]
I believe there is a typo here:

> 
> When integrating with Scrivener, the URLs generated will be based on the Plug.Conn's path. This can be overridden by passing in the page[:base_url] option.
> 
> `render conn, data: page, opts: [page: [base_url: "http://example.com/foos"]]`

Shouldn't it be

> `render conn, data: page, opts: [page: %{base_url: "http://example.com/foos"}]`

(a map instead of a list)

**Comment by beerlington** [comment]
I think there was a typo, but from what I could tell it was taking the base url from the top level opts (not from the page option):

```ex
render conn, "index.json-api", data: page, opts: [base_url: "http://example.com/foos"]
```

Updated the readme to reflect this.
