### ISSUE TITLE
Rendering of nested changeset errors

### ISSUE THREAD

**Issue by lpil** [vt-elixir/ja_serializer#249]
Hello!

I have an Ecto schema that `embeds_one` other schema. This results in a changeset that can have nested errors.

In my code it seems that the nested changeset's errors do not get rendered, is this the case or is my code incorrect in some fashion?

Cheers,
Louis

**Comment by edmaarcosta** [comment]
If you're interested, I solved a similar problem this way

```
  # changeset_view.ex
  def render("error.json", %Ecto.Changeset{} = changeset) do
    errors = 
      changeset
      |> translate_errors() # ecto extract and translate the errors
      |> traverse_detail() # give to function extract the details and format
      |> List.flatten 

    %{errors: errors}
  end
  
  def translate_errors(changeset) do
    Ecto.Changeset.traverse_errors(changeset, &translate_error/1)
  end

  defp traverse_detail(details) do
    Enum.map(details, fn {field, detail} ->
      cond do
        is_list(detail) -> 
          serializer_detail({field, detail})
        is_map(detail) -> 
          traverse_detail(detail)
        true -> %{}
      end
    end)
  end
  
  defp serializer_detail({field, detail}) do
    Enum.map(detail, fn title ->
      %{
        source: %{pointer: "/data/attributes/#{field}"},
        title: title,
        detail: "#{String.capitalize(field)} #{title}"
      }
    end)
  end
```

I don't know if that helps you

**Comment by coladarci** [comment]
We just ran into this as well - I think the correct way to solve this would be inside this library using https://hexdocs.pm/ecto/Ecto.Changeset.html#traverse_errors/2

**Comment by paveltyk** [comment]
JSON API does not allow nested resource objects, instead, it returns linked resources. I would expect `JaSerializer.PhoenixView.render_errors` to accept `[data: changeset, opts: [includes: "assoc_name1, assoc_name2"]]`. But it seems `render_errors` does not work that way. Does anyone know what is the proper way of rendering errors for associations?
