### ISSUE TITLE
Add custom/calculated attributes documentation

### ISSUE THREAD

**Issue by benoror** [vt-elixir/ja_serializer#259]
I had a hard time finding the info regarding virtual/calculated/custom attributes in the serializer's View. I finally found I was missing the params `(schema, _conn)` from the comments in the source code:

https://github.com/vt-elixir/ja_serializer/blob/master/lib/ja_serializer/dsl.ex#L27

**Comment by beerlington** [comment]
Hi @benoror sorry you weren't able to find the info you needed. I think the functionality is fairly well documented but am open to suggestions about how we can improve it https://hexdocs.pm/ja_serializer/JaSerializer.DSL.html#attributes/1

**Comment by benoror** [comment]
@beerlington sorry mate, I didn't saw that particular doc. I don't know if it would be worth having it somewhere in the README, nevertheless thanks for your response. Cheers! 🍻
