### ISSUE TITLE
has_one relationships don't need to always be loaded

### ISSUE THREAD

**Issue by InteNs** [vt-elixir/ja_serializer#267]
when I serialize a record with a has_one relation where it's not sideloaded the serializer doesn't really need the association to be loaded right? it only needs the `foreign_key` value and the `type`?

In order to save on database calls, is it possible to do this?

**Comment by atomkirk** [comment]
I just came here to open this issue. For reference, you can do this:

```elixir
has_one :account, type: "account", field: :account_id
```

This won't complain if its not preloaded. Unfortunately, if you DO want to sideload it, this won't work.

**Comment by rlivsey** [comment]
I'm currently working around this with the following style:

```elixir
has_one :city, serializer: MyApp.CityView

def preload(data, _conn, nil),     do: data
def preload(data, conn, preloads), do: data |> Repo.preload(preloads)

def city(%{city: %Ecto.Association.NotLoaded{}, city_id: nil}, _conn), do: nil
def city(%{city: %Ecto.Association.NotLoaded{}, city_id: id}, _conn), do: %{id: id}
def city(%{city: city}, _conn), do: city
```

So if the item isn't preloaded then it looks to the foreign key values, but if it is preloaded then returns the actual object to be serialized.

It's pretty repetitive though, I do this for every has_one in the app at the moment!

**Comment by doughsay** [comment]
@rlivsey database calls in your view layer are not a good idea.  If this serializer is invoked by an included `has_many` relationship from another serializer, then you get N+1 queries.

That being said, the overriding of the relationship getter like above does work.  It would be nice if ja_serializer did something like that for you automatically.  i.e. it should use a foreign_key field when the relationship was not requested to be included, and it should use the actual relationship when it was requested to be included. (making no assumptions about ecto / preloading, that's not up to the view layer)

**Comment by rlivsey** [comment]
@doughsay on my phone so can't double check, but I was under the impression that `preload` is only called at the top level - so this won't result in N+1 queries?

**Comment by doughsay** [comment]
Sorry @rlivsey, I actually had no idea that was a ja_serializer feature, I thought that was something you were doing manually.  In any case, I still stand by the idea that database calls should not ever happen in the view layer, so I'm dubious that this is a good feature for ja_serializer to even have...

**Comment by beerlington** [comment]
@john-griffin that's very familiar to me 😄

I think what @doughsay said above makes sense:

>  it should use a foreign_key field when the relationship was not requested to be included, and it should use the actual relationship when it was requested to be included.

I'll have to dig in a bit and see what it would take to do that.
