### ISSUE TITLE
Undefined function error, preload is not defined

### ISSUE THREAD

**Issue by mhanberg** [vt-elixir/ja_serializer#268]
Hi, hope everyone is doing well.

I have run into an error that I haven’t been able to overcome on my own and was looking for some guidance.

`** (UndefinedFunctionError) function ContactWeb.Api.V1.RoomSerializer.preload/3 is undefined (module ContactWeb.Api.V1.RoomSerializer is not available)`

I have attempted to implement the `preload` callback in my serializer, but the error persists. I have attached what I have currently in a gist.

One thing that is unique is that this is the first resource that I am serializing that has a few associations, some of which are nested. I am not sure if I am handling that correctly in my code. 

Any ideas would be appreciated! Thank you.

gist: https://gist.github.com/mhanberg/380e939b27a3bfe59b0ab76a28bcba00

**Comment by alanpeabody** [comment]
@mhanberg the error indicates the compiler could not find your module. Looking closely your serializer is named incorrectly (Rooms instead of Room).

✌️

**Comment by mhanberg** [comment]
Wow, that’s embarrassing 😅. 

Thank you!

**Comment by alanpeabody** [comment]
NP, I only noticed it because I have done similar things so many times before. :D
