### ISSUE TITLE
Empty "relationship object"

### ISSUE THREAD

**Issue by bundsol** [vt-elixir/ja_serializer#278]
According to the specification

   A “relationship object” **MUST** contain at least one of the following

But I have been receiving members in the 'relationships' field that are totally empty objects.
Something like
  
`relationships: {
      orders:{}
    }`

**Comment by johanb** [comment]
This is a duplicate of https://github.com/vt-elixir/ja_serializer/pull/235

**Comment by bundsol** [comment]
Thank you johanb. I hadn't seen it.
