### ISSUE TITLE
Unexpected behaviour of relationship identifiers

### ISSUE THREAD

**Issue by olivierpichon** [vt-elixir/ja_serializer#285]
Hey guys,

Thanks a lot for all the hard work you put on ja_serializer!

I am running into an issue currently where I am serializing a resource that can have an optional relationship. Let's call the resource `user` and its optional relationship `team`. This relationship is optional as in a user can have no team or one team.

In the serializer, I have:

```
  has_one(
    :team,
    serializer: Atlas.TeamView,
    type: "team"
  )
```

I see a different behaviour in the relationship identifiers when users include that team relationship ie when the team is preloaded or when it is not.

When it is not preloaded I get:
`"team" => %{"data" => %{"id" => "", "type" => "team"}}`

When it is preloaded I get:
`"team" => %{"data" => nil}`

This different behaviour makes it hard for users who consume the API. The preloaded form is also not compatible with our swagger.

Thanks for your feedback on this guys!

**Comment by lucas-nelson** [comment]
Same as #232 

Here we seem to have the same requirement as you, and are happy to let the business logic drive what to do in the views by the joins/preloads in the query. We've workaround the `nil` problem by making the a `JsonApiView` module available, and `use`ing it in place of `use JaSerializer.PhoenixView`.

```elixir
defmodule MyWeb.BlahResourceView do
  use MyWeb, :view
  use MyWeb.JsonApiView

  attributes […]

  …
end
```

```elixir
defmodule MyWeb.JsonApiView do
  defmacro __using__(_opts) do
    quote do
      use JaSerializer.PhoenixView

      # XXX: Internal knowledge of JaSerializer
      #
      # If a relationship has not been loaded in the resource, then filter it out
      # of the ja_serializer relationships map
      #
      # See; https://github.com/vt-elixir/ja_serializer/issues/232
      def relationships(struct, conn) do
        struct
        |> super(conn)
        |> Enum.filter(fn {assoc_name, _ja_relationship} ->
          struct
          |> Map.get(assoc_name)
          |> Ecto.assoc_loaded?
        end)
      end
      defoverridable [relationships: 2]
    end
  end
end
```

**Comment by olivierpichon** [comment]
Thx for the feedback @lucas-nelson, really helpful!
