### ISSUE TITLE
How to get nested attributes to also serialize?

### ISSUE THREAD

**Issue by broodfusion** [vt-elixir/ja_serializer#290]
Hello there,

Currently I'm having issues with returned JSON "attributes" field. Nested attributes are not serialized at all. 

FYI: I've tried this using a custom module key formatter, the built-in :underscore and :dasherized key formatter, but none of them helped

For example (using a camelize key formatter):
```
"attributes": {
    "firstName": "John",
    "lastName": "Doe",
    "stats": {
        "current_age": 29,
        "current_job": "teacher
    } 
}
```

In the above example, why are `current_age` and `current_job` in underscore format? Moreover, it seems ja_serializer is NOT serializing the nested attributes at all and just simply grabbing the names as they are in database. 

Regardless of what key formatter, whether using dasherize, underscore, or a custom key formatter, nested attributes don't seem to be serialized...or am I doing something wrong?

Thanks

**Comment by beerlington** [comment]
@broodfusion I haven't dug into it, but this is likely something that Ja Serializer doesn't currently have support for. I'd be happy to accept a PR for it though.
