### ISSUE TITLE
Considering migrating to Jason?

### ISSUE THREAD

**Issue by franckstifler** [vt-elixir/ja_serializer#303]
Jason is said to be the fastest Elixir JSON encoder, I would like to know if migrating to it is something planned?

**Comment by alanpeabody** [comment]
If you configure Plug/Phoenix to use Jason then you will be using Jason. This library doesn't actually convert into JSON, just to the properly formatted map to be passed to the JSON lib of your choice.

**Comment by beerlington** [comment]
@franckstifler I'm personally using JaSerializer + Jason in production on Phoenix 1.4 with the following config:

```ex
config :phoenix, :json_library, Jason
```

**Comment by franckstifler** [comment]
Thanks for your answers @beerlington  and @alanpeabody . I whish to know if and how ja_serializer handles %Ecto.Association.NotLoaded{} structs?

**Comment by beerlington** [comment]
@franckstifler can you be more specific?
