### ISSUE TITLE
Can not start app without poison

### ISSUE THREAD

**Issue by lasseebert** [vt-elixir/ja_serializer#309]
After https://github.com/vt-elixir/ja_serializer/pull/307, it is no longer possible to use ja_serializer without poison, since it is still part of the `applications` (in mix.exs)[https://github.com/vt-elixir/ja_serializer/blob/084125c5733733871a51cc3a0d4a5d3957592aa3/mix.exs#L21]

I guess this could just be replaced with `extra_applications: [:logger]`.

Will make a PR ;)

**Comment by greyhwndz** [comment]
Had this as a blocker in a recent Phoenix 1.4.4 app with `ja_serializer`.
I would like to request for a release of this please.
Thanks and more power!
