### ISSUE TITLE
phoenix 1.4.4 app errors due to Poison being required despite trying to use Jason

### ISSUE THREAD

**Issue by greyhwndz** [vt-elixir/ja_serializer#313]
There seems to be a PR that has addressed this but is not yet released:
https://github.com/vt-elixir/ja_serializer/commit/68f793b1f2fd4283fd4353d1ee5354878a490235
I would like to request for a release on this so I can go about with my app.
Thanks!

**Comment by beerlington** [comment]
@greyhwndz I'll see about getting a new release out soon, but in the mean time, you can just point your mix file to that commit to get the fix right now.

**Comment by greyhwndz** [comment]
@beerlington, is that commit based on `0.14.0`?

**Comment by beerlington** [comment]
@greyhwndz this is released in 0.14.1
