### ISSUE TITLE
Formatting keys of embedded objects

### ISSUE THREAD

**Issue by andrewtimberlake** [vt-elixir/ja_serializer#92]
If a model has an attribute that contains a map which in turn contains underscored keys, they are not formatted.
I see that Maps have been left without an implementation of the Formatter protocol.
I had a look around and implementing the Formatter protocol for Maps has far reaching effects.
Is this something that can be addressed by ja_serializer or should I just implement the protocol per project?

An example of what I’m talking about is,

``` elixir
render("show.json", conn: %{}, data: %{physical_address: %{line1: "line 1", postal_code: "1234"}))
```

is rendered as,

``` json
{"physical-address": {"line1": "line 1", "postal_code": "1234"}}
```

instead of,

``` json
{"physical-address": {"line1": "line 1", "postal-code": "1234"}}
```

The quick fix is,

``` elixir
defimpl JaSerializer.Formatter, for: Map do
  def format(map) do
    Enum.reduce(map, %{}, fn({key, val}, map) ->
      key = JaSerializer.Formatter.Utils.format_key(key)
      Map.put(map, key, JaSerializer.Formatter.format(val))
    end)
  end
end
```

**Comment by alanpeabody** [comment]
Great question. This is something I have gone back and forth on quite a bit.

Con: It would be a breaking change for sure and is then not overridable by users.

Pro: It seems like serializing maps that are not structs is a less likely scenario, and you can always define your own formatter for structs.

Pro: I also believe that if posting a map the keys are formatted, which means we have different behavior in different directions.

I am still wavering, but leaning towards including it.

**Comment by beerlington** [comment]
Fixed in https://github.com/vt-elixir/ja_serializer/pull/302
